language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-feed ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-reverseproxy

  - docker tag udagram-api-feed mysterious588/udagram-api-feed:v1
  - docker tag udagram-api-feed mysterious588/udagram-api-user:v1
  - docker tag udagram-api-feed mysterious588/udagram-frontend:v1
  - docker tag udagram-api-feed mysterious588/udagram-reverseproxy:v1
    
# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:  
  - docker push mysterious588/udagram-api-feed:v1
  - docker push mysterious588/udagram-api-user:v1   
  - docker push mysterious588/udagram-frontend:v1
  - docker push mysterious588/udagram-reverseproxy:v1
