language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-feed ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-reverseproxy

  - docker tag udagram-api-feed sudkul/udagram-api-feed:v1
  - docker tag udagram-api-feed sudkul/udagram-api-user:v1
  - docker tag udagram-api-feed sudkul/udagram-frontend:v1
  - docker tag udagram-api-feed sudkul/udagram-reverseproxy:v1
    
# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:  
  - docker push mysterious588/udagram-api-feed:v1
  - docker push mysterious588/udagram-api-user:v1   
  - docker push mysterious588/udagram-frontend:v1
  - docker push mysterious588/udagram-reverseproxy:v1

env:
  global:
  - secure: MiSZXvith2sWgoN64TnsDlIzVh02jrudxos51yUGg6pQfjarmATH2yJb6oF01XjyIyX0k8680hU82ZnMe5ol77RgLhJy0N2iszaj3m1c7atilgy7FHr5dlfSHwWeziEJIG6qg+3Jemsxexx4PeHmGTpoaC4EH+rZq6ImXZAgIt7tsvfZfWpV3sn4ccObBP4RBwB+3FhzQhOPwIHVYoajNmyMz2mus9qGRGC15RpRwbdVgmUQdmb5VcjSj4gfYffSeKyJ773Myw0rUOSJRFlrhkpJ/V4oXFwh6xyvdg3KiltiLTtIv8gZ7L9Chg9Uaekg031hxN39yoCgy5jvmdzoNtwq6/CKhg6tXarsUOViVFy1edKiFw23KTX915tjixy7wEy/Dx9VnbxA1S8GkHxNwdIRntAxXVjgtjR7pKWLr9u3s4o6+Lr1N973cTP9Yk8m5t+wZzkAnT80WUzUCYvm6OOnv8vBG2Ue9lrikE1qv8gZQD4kSTexk+V3BcTC6ZTFCYPLcMGf9uG+5Wmrv06FJEMJtrGyeSLyUPt+LjsL7Zpnyn905cqM69JFUXKLjsS7qoUaAgQ0FSGqz7h9zpWFf64xvV0yqZgCaJyCD982rJBXo2GaDuXvn+qR/OtOaQ9uJjdUCArykU759gvMdQCWE+wu7KljWi+5gSP/OCYAbz0=
  - secure: df8hEuIHzZ/GlmZEmgYEstMIGQ48rn4UP6kJxQtQpD1g7LPoDnyfdv8SQENcBh2WBw/lMYzBxDp4Y4+F2MiwqcFIPRiC1OugoNLcwYXbHFI3y15b65uZLvc5PZE0c/GBP/oIL/t37knz+peanPuhmDgfwexfHdiaKLDB+X62tUJTDkZHiQmNHzFQ21zi+EzbAIV+oEnsMIOrpCjq4/mmOTnJ+IN+GV05VJU6Lw3b676Sjwlbm63E9t6i1joR04jOuTnOixBcIwjMMDUC2IhyR9vi27yd0HnMvX9e8ipLCmmk/PpKGBDt0s/NMV63lDNWr+xr4lVe5GztuAzW/llNCRyKhnNFHLy4MhnMLdbqBB0685pQoa17X5WF4jGItQX3yGBmqF0xrvUAi0yMY3kqJ5Y7wsjyZookvmuwtEXMUyVwvPrrrmlyAXyU2Hih29DIkLU7i+6hwChro2NFQfj7F1yGZZtow/rucCgWwR4abi94inYZgM0VrRJ7IobHGVy7CreqPUxIVC/vcwhaIXWEsNtpi4hIk7Rdusts7ZdVf3QO7dKiz17qGK/h/jO4XpnF29kae5vEvt0F7rroPOYpap6NrnhkMkHoHibzmoZkggs3Ib987UUFF+7N4NMRGhqT2cfX0ehtx5rFRevUz2ADY4yi8kOZySX2r2MqtPzf4gw=
